# Generated by Django 3.0.8 on 2020-09-20 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='Customer',
        ),
    ]
