# Generated by Django 3.0.8 on 2020-10-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customer_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='videofile',
            field=models.FileField(blank=True, default='video_null.mp4', null=True, upload_to=''),
        ),
    ]
