# Generated by Django 3.0.8 on 2020-10-18 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_auto_20201017_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(blank=True, choices=[('Comedy', 'Comedy'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=25, null=True)),
                ('videofilel', models.FileField(blank=True, null=True, upload_to='')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
