# Generated by Django 3.0.8 on 2020-10-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='customer',
            field=models.ManyToManyField(to='accounts.Customer'),
        ),
    ]
