# Generated by Django 3.0.8 on 2020-10-19 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_file_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='customer',
        ),
        migrations.AddField(
            model_name='file',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer'),
        ),
    ]
