# Generated by Django 3.0.8 on 2020-10-19 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201018_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='date_uploaded',
            new_name='upload_date_and_time',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='videofilel',
            new_name='upload_video',
        ),
    ]
