# Generated by Django 3.0.8 on 2020-10-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20201019_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.CharField(blank=True, choices=[('Comedy', 'Comedy'), ('Fitness', 'Fitness'), ('Cooking', 'Cooking'), ('Entertainment', 'Entertainment'), ('Technology', 'Technology'), ('Other', 'Other')], max_length=25, null=True),
        ),
    ]
