# Generated by Django 3.0.8 on 2020-11-08 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='chat_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Chat'),
        ),
    ]
