# Generated by Django 3.0.8 on 2020-11-09 02:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0022_auto_20201108_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content_viewers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='premium',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
