# Generated by Django 3.0.8 on 2020-11-09 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20201108_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='chat_list',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
