# Generated by Django 3.0.8 on 2020-11-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20201108_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='thumb_nail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
