# Generated by Django 3.0.8 on 2020-11-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_file_thumb_nail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='description',
            new_name='title',
        ),
    ]
