# Generated by Django 3.0.8 on 2020-11-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20201121_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscribe_poster',
            field=models.ImageField(blank=True, default='profile_null.png', null=True, upload_to=''),
        ),
    ]
