# Generated by Django 3.0.8 on 2020-11-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20201121_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscriber',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
