# Generated by Django 3.0.8 on 2020-11-22 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_customer_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='subscriber',
        ),
    ]
