# Generated by Django 3.0.8 on 2020-11-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_customer_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscriber',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
