# Generated by Django 3.0.8 on 2020-11-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20201121_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscriber',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
