# Generated by Django 3.0.8 on 2020-11-22 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20201121_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='subscriber',
            new_name='subscribe',
        ),
    ]
