# Generated by Django 3.0.8 on 2020-11-27 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_customer_saved_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='saved_videos',
        ),
    ]
