# Generated by Django 3.0.8 on 2020-11-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_remove_customer_saved_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='saved_videos',
            field=models.ManyToManyField(related_name='_customer_saved_videos_+', to='accounts.File'),
        ),
    ]
