# Generated by Django 3.0.8 on 2020-11-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_customer_saved_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='saved_videos',
        ),
        migrations.AddField(
            model_name='customer',
            name='saved_files',
            field=models.ManyToManyField(related_name='_customer_saved_files_+', to='accounts.File'),
        ),
    ]
