# Generated by Django 3.0.8 on 2020-11-29 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_stripecustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='subscribe',
        ),
    ]
