# Generated by Django 3.0.8 on 2020-11-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_remove_customer_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscribe',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
