# Generated by Django 3.0.8 on 2020-11-29 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_customer_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='user',
            new_name='stripe_user',
        ),
    ]
