# Generated by Django 3.0.8 on 2020-11-29 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20201129_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='stripe_user',
            new_name='user',
        ),
    ]
